name: OpenTpa
version: '${project.version}'
main: com.seajee.opentpa.OpenTpa
api-version: '1.20'
commands:
  tpa:
    description: Sends a tpa request to a player
    usage: /tpa <player>
    permission: opentpa.tpa
  tpaccept:
    description: Accepts a tpa request
    usage: /tpaccept <request>
    permission: opentpa.tpaccept
  tpacancel:
    description: Cancels a tpa request
    usage: /tpacancel
    permission: opentpa.tpacancel
